
package client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@javax.jws.WebService(name = "WebService", targetNamespace = "http://www.service.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebService {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "register", targetNamespace = "http://www.service.com", className = "client.Register")
    @ResponseWrapper(localName = "registerResponse", targetNamespace = "http://www.service.com", className = "client.RegisterResponse")
    @Action(input = "http://www.service.com/WebService/registerRequest", output = "http://www.service.com/WebService/registerResponse")
    public String register(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "queryItem", targetNamespace = "http://www.service.com", className = "client.QueryItem")
    @ResponseWrapper(localName = "queryItemResponse", targetNamespace = "http://www.service.com", className = "client.QueryItemResponse")
    @Action(input = "http://www.service.com/WebService/queryItemRequest", output = "http://www.service.com/WebService/queryItemResponse")
    public String queryItem(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "clearAll", targetNamespace = "http://www.service.com", className = "client.ClearAll")
    @ResponseWrapper(localName = "clearAllResponse", targetNamespace = "http://www.service.com", className = "client.ClearAllResponse")
    @Action(input = "http://www.service.com/WebService/queryItemRequest", output = "http://www.service.com/WebService/queryItemResponse")
    public String clearAll(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteItem", targetNamespace = "http://www.service.com", className = "client.DeleteItem")
    @ResponseWrapper(localName = "deleteItemResponse", targetNamespace = "http://www.service.com", className = "client.DeleteItemResponse")
    @Action(input = "http://www.service.com/WebService/deleteItemRequest", output = "http://www.service.com/WebService/deleteItemResponse")
    public String deleteItem(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addItem", targetNamespace = "http://www.service.com", className = "client.AddItem")
    @ResponseWrapper(localName = "addItemResponse", targetNamespace = "http://www.service.com", className = "client.AddItemResponse")
    @Action(input = "http://www.service.com/WebService/addItemRequest", output = "http://www.service.com/WebService/addItemResponse")
    public String addItem(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3);

}
