
package com.javaedu;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "hello", targetNamespace = "http://www.javaedu.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Hello {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "hello", targetNamespace = "http://www.javaedu.com", className = "com.javaedu.Hello_Type")
    @ResponseWrapper(localName = "helloResponse", targetNamespace = "http://www.javaedu.com", className = "com.javaedu.HelloResponse")
    @Action(input = "http://www.javaedu.com/hello/helloRequest", output = "http://www.javaedu.com/hello/helloResponse")
    public String hello(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHi", targetNamespace = "http://www.javaedu.com", className = "com.javaedu.SayHi")
    @ResponseWrapper(localName = "sayHiResponse", targetNamespace = "http://www.javaedu.com", className = "com.javaedu.SayHiResponse")
    @Action(input = "http://www.javaedu.com/hello/sayHiRequest", output = "http://www.javaedu.com/hello/sayHiResponse")
    public String sayHi(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

}
